name: Deploy to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  create-app-registration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Create App Registration and Service Principal
      id: create_sp
      run: |
        appName="AKSServicePrincipal"
        password=$(az ad sp create-for-rbac --name $appName --skip-assignment --query password --output tsv)
        appId=$(az ad sp show --id http://$appName --query appId --output tsv)
        tenantId=$(az account show --query tenantId --output tsv)
        subscriptionId=$(az account show --query id --output tsv)

        echo "AZURE_CLIENT_ID=$appId" >> $GITHUB_ENV
        echo "AZURE_CLIENT_SECRET=$password" >> $GITHUB_ENV
        echo "AZURE_TENANT_ID=$tenantId" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=$subscriptionId" >> $GITHUB_ENV

    - name: Assign Roles to Service Principal
      run: |
        az role assignment create --assignee ${{ env.AZURE_CLIENT_ID }} --role Contributor --scope /subscriptions/${{ env.AZURE_SUBSCRIPTION_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: create-app-registration

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bicep
      uses: Azure/setup-bicep@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ env.AZURE_CLIENT_SECRET }}

    - name: Deploy Bicep
      run: |
        az deployment group create \
          --resource-group <resource-group-name> \
          --template-file bicep/main.bicep \
          --parameters @json/aks.json