name: Deploy to Azure
run-name: ${{ github.actor }} started deployment AVD and AKS with GitHub Actions

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

defaults: 
  run:
    shell: pwsh

env:
  TenantID: ${{ secrets.TENANT_ID }}
  AppID: ${{ secrets.AZURELOCALSOLUTIONIAC_CLIENTID }}
  Subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  Location: 'norwayeast'
  aks-resourceGroupName: 'aks-kubernetes-arc-rg'
  avd-resourceGroupName: 'avd-resource-group'
  aksKeyVaultName: 'aks-keyvault'
  avdKeyVaultName: 'avd-keyvault'
  aksCluster1ClientID: ${{ secrets.COOLAKSCLUSTER1_CLIENTID }}
  aksCluster1Secret: ${{ secrets.COOLAKSCLUSTER1_SECRET }}
  aksCluster2ClientID: ${{ secrets.COOLAKSCLUSTER2_CLIENTID }}
  aksCluster2Secret: ${{ secrets.COOLAKSCLUSTER2_SECRET }}
  
jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
      environmentName: dev

    steps:
    - name: 🤑💸Checkout parameter
      uses: actions/checkout@v3

    - name: Install Azure module to resolve Token issue
      uses: ./.github/actions/az-install
      with:
        version: 13.2.0          # This version of PS remediates the OIDC token expiry issue - #10249

    - name: 🥳 Connect to Azure
      id: azure-login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURELOCALSOLUTIONIAC_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Install PowerShell Modules
      shell: pwsh
      run: |
        Install-Module Az.Accounts -Force
        Install-Module Az.Resources -Force
        Install-Module Az.Network -Force
        Install-Module Az.Compute -Force
        Install-Module -Name AzureAD -Force -AllowClobber
        Install-Module -Name Microsoft.PowerShell.SecretManagement -Repository PSGallery -Force
        Install-Module Az.KeyVault -Repository PSGallery -Force

    - name: Deploy Resource Groups and Create Key Vaults for AKS and AVD
      shell: pwsh
      run: |
        New-AzSubscriptionDeployment -Name "Deployment-DEV-${{ github.actor }}-$(get-random)" `
          -TemplateFile "bicep/deploy.rg_kv.bicep" `
          -TemplateParameterFile "json/deploy.rg_kv.json" `
          -location "${{ env.Location }}" `
          -tenantId "${{ secrets.AZURE_TENANT_ID }}"

    - name: Generate and Store SSH Keys in Key Vaults for AKS and AVD
      shell: pwsh
      run: |
        $sshDir = "$env:HOME/.ssh"
        if (-Not (Test-Path -Path $sshDir)) {
          New-Item -ItemType Directory -Force -Path $sshDir
        }
        # Generate SSH keys locally
        ssh-keygen -t rsa -b 4096 -f "$sshDir/sshkey-aks-kubernetes-arc-rg-dev" -N ""
        ssh-keygen -t rsa -b 4096 -f "$sshDir/sshkey-avd-resource-group-dev" -N ""

        # Store SSH private keys in Key Vaults
        $privateKeyAks = Get-Content -Raw -Path "$sshDir/sshkey-aks-kubernetes-arc-rg-dev"
        $privateKeyAvd = Get-Content -Raw -Path "$sshDir/sshkey-avd-resource-group-dev"
        Set-AzKeyVaultSecret -VaultName "${{ env.aksKeyVaultName }}" -Name "SSHPrivateKeyAks" -SecretValue (ConvertTo-SecureString -String $privateKeyAks -AsPlainText -Force)
        Set-AzKeyVaultSecret -VaultName "${{ env.avdKeyVaultName }}" -Name "SSHPrivateKeyAvd" -SecretValue (ConvertTo-SecureString -String $privateKeyAvd -AsPlainText -Force)

        # Store SSH public keys in Key Vaults
        $publicKeyAks = Get-Content -Raw -Path "$sshDir/sshkey-aks-kubernetes-arc-rg-dev.pub"
        $publicKeyAvd = Get-Content -Raw -Path "$sshDir/sshkey-avd-resource-group-dev.pub"
        Set-AzKeyVaultSecret -VaultName "${{ env.aksKeyVaultName }}" -Name "SSHPublicKeyAks" -SecretValue (ConvertTo-SecureString -String $publicKeyAks -AsPlainText -Force)
        Set-AzKeyVaultSecret -VaultName "${{ env.avdKeyVaultName }}" -Name "SSHPublicKeyAvd" -SecretValue (ConvertTo-SecureString -String $publicKeyAvd -AsPlainText -Force)

    - name: Deploy Azure Local and Connect On-Prem
      shell: pwsh
      run: |
        $resourceGroupName = "aks-kubernetes-arc-rg-dev"
        $location = "norwayeast"
        $machineName = "PCNOR262914"

        # Install Azure PowerShell
        Install-Module -Name Az -AllowClobber -Scope CurrentUser

        # Login to Azure
        Connect-AzAccount

        # Create Resource Group
        New-AzResourceGroup -Name $resourceGroupName -Location $location

        # Install the Connected Machine Agent
        Install-Module -Name Az.ConnectedMachine

        # Register the Machine with Azure Arc
        Connect-AzConnectedMachine -ResourceGroupName $resourceGroupName -Name $machineName -Location $location

    - name: Deploy Bicep for AKS
      shell: pwsh
      run: |
        $aksCluster1ClientID = ConvertTo-SecureString -String "${{ secrets.COOLAKSCLUSTER1_CLIENTID }}" -AsPlainText -Force
        $aksCluster1ClientSecret = ConvertTo-SecureString -String "${{ secrets.COOLAKSCLUSTER1_SECRET }}" -AsPlainText -Force
        $aksCluster2ClientID = ConvertTo-SecureString -String "${{ secrets.COOLAKSCLUSTER2_CLIENTID }}" -AsPlainText -Force
        $aksCluster2ClientSecret = ConvertTo-SecureString -String "${{ secrets.COOLAKSCLUSTER2_SECRET }}" -AsPlainText -Force

        New-AzSubscriptionDeployment -Name "Deployment-DEV-${{ github.actor }}-$(get-random)" `
          -TemplateFile "bicep/main.bicep" `
          -resourceGroupName "${{ env.aks-resourceGroupName }}-${{ env.environmentName }}" `
          -subscriptionId "${{ secrets.AZURE_SUBSCRIPTION_ID }}" `
          -TemplateParameterFile "json/aks.json" `
          -location "${{ env.Location }}" `
          -tenantId "${{ secrets.AZURE_TENANT_ID }}" `
          -aksCluster1ClientID $aksCluster1ClientID `
          -aksCluster1ClientSecret $aksCluster1ClientSecret `
          -aksCluster2ClientID $aksCluster2ClientID `
          -aksCluster2ClientSecret $aksCluster2ClientSecret

